spring:
  application:
    name: mindme-backend
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/mindme
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379

langchain4j:
  open-ai:
    chat-model:
      api-key: ${OPENAI_API_KEY:}
      base-url: ${OPENAI_BASE_URL:https://integrate.api.nvidia.com/v1}
      model-name: ${OPENAI_MODEL:moonshotai/kimi-k2-thinking}
      timeout: PT60S
    embedding-model:
      api-key: ${OPENAI_API_KEY:}
      base-url: ${OPENAI_BASE_URL:https://integrate.api.nvidia.com/v1}
      model-name: nvidia/nv-embed-v1
  pgvector:
    host: localhost
    port: 5432
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    database: mindme
    table: vector_store
    dimension: 1024 # Depends on embedding model
    drop-table-first: false
    create-table-if-not-exists: true
    index-type: HNSW

server:
  port: 8091
